# 优先级，bootstrap.yaml 高于 application-dev.yaml，所以 nacos 的配置一定要配置在 bootstrap.yaml 中
server:
  port: 80

spring:
  application:
    name: ys-medical-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name:  com.mysql.cj.jdbc.Driver #mysql 驱动包
    url: jdbc:mysql://localhost:3306/ys-medical-payment?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root

# 基于 eureka 服务注册中心
eureka:
  client:
    # 表示是否将自己注册进 eureka server，默认为 true
    register-with-eureka: true
    # 是否从 eureka server 抓取已有的注册信息，默认为 true，单节点无所谓，集群必须设置为 true 才能配合 ribbon 使用负载均衡
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

mybatis:
  mapperLocations: classpath:mapper/*.xml # xml 文件的位置
  type-aliases-package: com.ys.entity #所有entity别名类所在包