server:
  port: 3344

spring:
  application:
    name: ys-medical-config # 注册到 eureka 服务器的服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ys-018/ys-medical-housekeepers.git # github 上面的 git 仓库名称
          # 搜索目录
          search-paths:
            - ys-medical-housekeepers
          force-pull: true
          username: ys-018
          password: 786165993wdz018 # 注意这里还有一个 passphrase: ,千万别写错，不然搞死你
      label: master # 读取分支
# curl -X POST http://localhost:3344/actuator/bus-refresh 消息总线全部刷新，在 cmd 中
# curl -X POST http://localhost:3344/actuator/bus-refresh/ys-medical-config-client:3355 消息定点刷新，只刷新3355
# RabbitMQ 相关配置
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka


# RabbitMQ 相关配置，暴露 bus 刷新配置的端点
management:
  endpoints: # 暴露 bus 刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
